### ISSUE TITLE
pedestrian_0817 missing

### ISSUE THREAD

**Issue by MounirB** [godisreal/Many-Particle-System#4]
Hello,
The class pedestrian_0817 as well as particle_Regroup and math_func are missing in your repository. They are needed by all the simulators.

Can you add them please ?

**Comment by godisreal** [comment]
The repo has been partly updated.  
Thanks for your interest.  Comemnts and pull request are much appreciated.

**Comment by MounirB** [comment]
Thank you for updating it !
